name: 'gh-npm'
description: 'Multi-publish to both GitHub and NPM Package registry'
branding:
  icon: package
  color: purple

inputs:
  node_version:
    description: 'Node.js version'
    required: true
  npm_scope:
    description: 'NPM scope'
    required: true
  github_scope:
    description: 'GitHub scope'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
      shell: bash

    - name: NPM Publish
      run: |
        npm ci
        npm publish --access public
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: GitHub Publish
      run: |
        npm ci
        npm publish --access public
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
