name: gh-npm
description: Multi-publish to both GitHub and NPM Package registry
branding:
  icon: package
  color: purple

inputs:
  node_version:
    description: 'Node.js version'
    default: '12'

  npm_scope:
    description: 'NPM scope'
    required: true

  github_scope:
    description: 'GitHub scope'
    required: true

runs:
  using: 'composite'
  shell: bash
  steps:
    - name: Install Dependencies
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: 'https://registry.npmjs.org'
      run: npm ci

    - name: Checkout code
      uses: actions/checkout@v4

    - name: NPM Publish
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: 'https://registry.npmjs.org'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: npm publish --access public

    - name: GitHub Publish
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: 'https://npm.pkg.github.com'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm publish --access public
